info:
  contact: {}
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token
      produces:
      - application/json
      responses: {}
      summary: Login a user
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user with a username and password
      produces:
      - application/json
      responses: {}
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
